### ISSUE TITLE
Support for floats

### ISSUE THREAD

**Issue by ryansmith94** [ryansmith94/baseroo#2]
This has been requested by various people.

- https://stackoverflow.com/questions/1337419/how-do-you-convert-numbers-between-different-bases-in-javascript/32480941#comment58147890_32480941
- https://gist.github.com/ryansmith94/91d7fd30710264affeb9?permalink_comment_id=1689874#gistcomment-1689874

**Comment by c0ncentus** [comment]
@ryansmith94  any news about this ?

**Comment by ryansmith94** [comment]
Nothing at the moment @c0ncentus - need some time to consider how to do it.
